-- AlterTable
ALTER TABLE "Server" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ServerData" ADD COLUMN     "last_update" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
